In [1]:
import numpy as np
import sympy as sp
from tetb import *

In [2]:
irreps_names = [
    "G1p",
    "G1m",
    "G2p",
    "G2m",
    "G3p",
    "G3m",
    "G4p",
    "G4m",
    "G5p",
    "G5m",
    "R1p",
    "R1m",
    "R2p",
    "R2m",
    "R3p",
    "R3m",
    "R4p",
    "R4m",
    "R5p",
    "R5m",
    "M1",
    "M2",
    "M3",
    "M4",
    "X1",
    "X2",
    "X3",
    "X4",
]

N_gamma = 10

ebrs_names = [
    "A1_2a",
    "A2_2a",
    "E_2a",
    "T1_2a",
    "T2_2a",
    "A1g_4b",
    "A1u_4b",
    "A2g_4b",
    "A2u_4b",
    "Eg_4b",
    "Eu_4b",
    "A1g_4c",
    "A1u_4c",
    "A2g_4c",
    "A2u_4c",
    "Eg_4c",
    "Eu_4c",
    "A1_6d",
    "A2_6d",
    "B1_6d",
    "B2_6d",
    "A1_12f",
    "B1_12f",
    "B2_12f",
    "B3_12f",
]

dim_ebrs = [
    2,
    2,
    4,
    6,
    6,
    4,
    4,
    4,
    4,
    8,
    8,
    4,
    4,
    4,
    4,
    8,
    8,
    6,
    6,
    6,
    6,
    12,
    12,
    12,
    12,
]

In [3]:
irreps = sp.var(names=irreps_names)
ebrs = sp.var(names=ebrs_names)

In [4]:
EBR = np.stack(
    (
        ir2vec(G1p + G2m + R1p + R2m + M1 + X1, irreps),
        ir2vec(G1m + G2p + R1m + R2p + M2 + X2, irreps),
        ir2vec(G3p + G3m + R3p + R3m + M1 + M2 + X1 + X2, irreps),
        ir2vec(G4p + G5m + R4p + R5m + M2 + M3 + M4 + X2 + X3 + X4, irreps),
        ir2vec(G4m + G5p + R4m + R5p + M1 + M3 + M4 + X1 + X3 + X4, irreps),
        ir2vec(G1p + G5p + R1p + R5p + M1 + M3 + X1 + X4, irreps),
        ir2vec(G1m + G5m + R1m + R5m + M2 + M3 + X2 + X4, irreps),
        ir2vec(G2p + G4p + R2p + R4p + M2 + M4 + X2 + X3, irreps),
        ir2vec(G2m + G4m + R2m + R4m + M1 + M4 + X1 + X3, irreps),
        ir2vec(
            G3p + G4p + G5p + R3p + R4p + R5p + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(
            G3m + G4m + G5m + R3m + R4m + R5m + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(G1p + G5p + R2m + R4m + M1 + M3 + X1 + X3, irreps),
        ir2vec(G1m + G5m + R2p + R4p + M2 + M3 + X2 + X3, irreps),
        ir2vec(G2p + G4p + R1m + R5m + M2 + M4 + X2 + X4, irreps),
        ir2vec(G2m + G4m + R1p + R5p + M1 + M4 + X1 + X4, irreps),
        ir2vec(
            G3p + G4p + G5p + R3m + R4m + R5m + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(
            G3m + G4m + G5m + R3p + R4p + R5p + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(G1p + G2m + G3p + G3m + R4m + R5p + M1 + M3 + M4 + 2 * X1 + X2, irreps),
        ir2vec(G4p + G5m + R1m + R2p + R3p + R3m + M1 + 2 * M2 + X2 + X3 + X4, irreps),
        ir2vec(G1m + G2p + G3p + G3m + R4p + R5m + M2 + M3 + M4 + X1 + 2 * X2, irreps),
        ir2vec(G4m + G5p + R1p + R2m + R3p + R3m + 2 * M1 + M2 + X1 + X3 + X4, irreps),
        ir2vec(
            G1p
            + G1m
            + G3p
            + G3m
            + G5p
            + G5m
            + R4p
            + R4m
            + R5p
            + R5m
            + M1
            + M2
            + 3 * M3
            + M4
            + 2 * X1
            + 2 * X2
            + X3
            + X4,
            irreps,
        ),
        ir2vec(
            G2p
            + G2m
            + G3p
            + G3m
            + G4p
            + G4m
            + R4p
            + R4m
            + R5p
            + R5m
            + M1
            + M2
            + M3
            + 3 * M4
            + 2 * X1
            + 2 * X2
            + X3
            + X4,
            irreps,
        ),
        ir2vec(
            G4p
            + G4m
            + G5p
            + G5m
            + R1p
            + R1m
            + R3p
            + R3m
            + R5p
            + R5m
            + 2 * M1
            + 2 * M2
            + M3
            + M4
            + X1
            + X2
            + X3
            + 3 * X4,
            irreps,
        ),
        ir2vec(
            G4p
            + G4m
            + G5p
            + G5m
            + R2p
            + R2m
            + R3p
            + R3m
            + R4p
            + R4m
            + 2 * M1
            + 2 * M2
            + M3
            + M4
            + X1
            + X2
            + 3 * X3
            + X4,
            irreps,
        ),
    ),
    axis=1,
)

In [5]:
print(EBR)

[[1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0]
 [0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 1]
 [0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 1 1]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1]
 [0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 1]
 [0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 1 

In [6]:
print(ebr2irvec(v=A2g_4b + Eu_4b, ebrs=ebrs, EBR=EBR))

[0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 2 1 2 1 2 2 1]


In [7]:
c = G2m + G4m + R4m + R5p + M1 + 2 * M4 + X1 + X3 + X4
v = ir2vec(v=c, irreps=irreps)
print(v)

[0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 2 1 0 1 1]


In [8]:
n = searchForAllLongModes(dim=dim_ebrs, t=2)
print(n.solutions())

[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [9]:
rv = np.delete(v, range(N_gamma))  # type: ignore
rEBR = np.delete(EBR, range(N_gamma), axis=0)  # type: ignore

In [10]:
searchForAll_EBRs(rv, dim_ebrs, rEBR, n.solutions())

[array([], dtype=float64),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]])]

In [12]:
showAllResults(v, 2, dim_ebrs, EBR, N_gamma, ebrs, irreps, SG=224)

[([A2u_4b + A2u_4c], A1_2a, [True], [-G1p + G4m])]

In [44]:
model = cp_model.CpModel()
solver = cp_model.CpSolver()
x = [model.new_int_var(0, 1000, f"x{i}") for i in range(np.shape(A)[1])]
solutionObtainer = varArraySolutionObtainer(x)

for j in range(len(z)):
    model.add(A[j] @ x == y[j])

solver.parameters.enumerate_all_solutions = True
status = solver.solve(model, solutionObtainer)
solutionObtainer.solutionCount()

0

In [39]:
A = np.array(
    [
        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0],
        [1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 2],
        [0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 2],
        [0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 3, 1, 1, 1],
        [0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 3, 1, 1],
        [1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 0, 1, 1, 2, 2, 1, 1],
        [0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 2, 1, 1],
        [0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 3],
        [0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 3, 1],
    ]
)

z = np.array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 1, 1])

In [40]:
model = cp_model.CpModel()
solver = cp_model.CpSolver()
x = [model.new_int_var(0, 1000, f"x{i}") for i in range(np.shape(A)[1])]
solutionObtainer = varArraySolutionObtainer(x)

for j in range(len(z)):
    model.add(A[j] @ x == z[j])

solver.parameters.enumerate_all_solutions = True
status = solver.solve(model, solutionObtainer)
solutionObtainer.solutionCount()

1

In [41]:
solutionObtainer.solutions()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [42]:
print((A == rEBR).all())
print((y == z).all())

True
True


In [43]:
x = ebr2vec(A2u_4b + A2u_4c, ebrs)

for j in range(N_irr):
    print(rEBR[j] @ x == rv[j] + (rEBR[j] @ n.solutions()[1]))

print(x)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
