# Implementing the package to find a TETB model in SG #224 for the crystal studied in this [article](https://arxiv.org/abs/2305.18257)

In [3]:
import numpy as np
import sympy as sp
from tetb import *

## Define the irreps and EBRs names in SG #224.

In [4]:
irreps_names = [
    "G1p",
    "G1m",
    "G2p",
    "G2m",
    "G3p",
    "G3m",
    "G4p",
    "G4m",
    "G5p",
    "G5m",
    "R1p",
    "R1m",
    "R2p",
    "R2m",
    "R3p",
    "R3m",
    "R4p",
    "R4m",
    "R5p",
    "R5m",
    "M1",
    "M2",
    "M3",
    "M4",
    "X1",
    "X2",
    "X3",
    "X4",
]

N_gamma = 10 # numero de irreps en Gamma

ebrs_names = [
    "A1_2a",
    "A2_2a",
    "E_2a",
    "T1_2a",
    "T2_2a",
    "A1g_4b",
    "A1u_4b",
    "A2g_4b",
    "A2u_4b",
    "Eg_4b",
    "Eu_4b",
    "A1g_4c",
    "A1u_4c",
    "A2g_4c",
    "A2u_4c",
    "Eg_4c",
    "Eu_4c",
    "A1_6d",
    "A2_6d",
    "B1_6d",
    "B2_6d",
    "A1_12f",
    "B1_12f",
    "B2_12f",
    "B3_12f",
]

dim_ebrs = [
    2,
    2,
    4,
    6,
    6,
    4,
    4,
    4,
    4,
    8,
    8,
    4,
    4,
    4,
    4,
    8,
    8,
    6,
    6,
    6,
    6,
    12,
    12,
    12,
    12,
]

In [5]:
irreps = sp.var(names=irreps_names)
ebrs = sp.var(names=ebrs_names)

You can print now the irreps and ebrs to see how Python encodes them. This is crucial to have it clear since you need to respect that notation for now on.

In [6]:
print(irreps)
print(ebrs)

[G1p, G1m, G2p, G2m, G3p, G3m, G4p, G4m, G5p, G5m, R1p, R1m, R2p, R2m, R3p, R3m, R4p, R4m, R5p, R5m, M1, M2, M3, M4, X1, X2, X3, X4]
[A1_2a, A2_2a, E_2a, T1_2a, T2_2a, A1g_4b, A1u_4b, A2g_4b, A2u_4b, Eg_4b, Eu_4b, A1g_4c, A1u_4c, A2g_4c, A2u_4c, Eg_4c, Eu_4c, A1_6d, A2_6d, B1_6d, B2_6d, A1_12f, B1_12f, B2_12f, B3_12f]


### Construct the matrix of EBRs in a easy way using the functions we implemented.

You can build the EBR matrix, represented by `A` in the [article](https://arxiv.org/abs/2305.18257), by placing the "symmetry vectors" of EBRs as columns.

We implemented a function `ir2vec` that transform a sum of irreps into a "symmetry vector", so the matrix `A` can be built as

In [7]:
A = np.stack(
    (
        ir2vec(G1p + G2m + R1p + R2m + M1 + X1, irreps),
        ir2vec(G1m + G2p + R1m + R2p + M2 + X2, irreps),
        ir2vec(G3p + G3m + R3p + R3m + M1 + M2 + X1 + X2, irreps),
        ir2vec(G4p + G5m + R4p + R5m + M2 + M3 + M4 + X2 + X3 + X4, irreps),
        ir2vec(G4m + G5p + R4m + R5p + M1 + M3 + M4 + X1 + X3 + X4, irreps),
        ir2vec(G1p + G5p + R1p + R5p + M1 + M3 + X1 + X4, irreps),
        ir2vec(G1m + G5m + R1m + R5m + M2 + M3 + X2 + X4, irreps),
        ir2vec(G2p + G4p + R2p + R4p + M2 + M4 + X2 + X3, irreps),
        ir2vec(G2m + G4m + R2m + R4m + M1 + M4 + X1 + X3, irreps),
        ir2vec(
            G3p + G4p + G5p + R3p + R4p + R5p + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(
            G3m + G4m + G5m + R3m + R4m + R5m + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(G1p + G5p + R2m + R4m + M1 + M3 + X1 + X3, irreps),
        ir2vec(G1m + G5m + R2p + R4p + M2 + M3 + X2 + X3, irreps),
        ir2vec(G2p + G4p + R1m + R5m + M2 + M4 + X2 + X4, irreps),
        ir2vec(G2m + G4m + R1p + R5p + M1 + M4 + X1 + X4, irreps),
        ir2vec(
            G3p + G4p + G5p + R3m + R4m + R5m + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(
            G3m + G4m + G5m + R3p + R4p + R5p + M1 + M2 + M3 + M4 + X1 + X2 + X3 + X4,
            irreps,
        ),
        ir2vec(G1p + G2m + G3p + G3m + R4m + R5p + M1 + M3 + M4 + 2 * X1 + X2, irreps),
        ir2vec(G4p + G5m + R1m + R2p + R3p + R3m + M1 + 2 * M2 + X2 + X3 + X4, irreps),
        ir2vec(G1m + G2p + G3p + G3m + R4p + R5m + M2 + M3 + M4 + X1 + 2 * X2, irreps),
        ir2vec(G4m + G5p + R1p + R2m + R3p + R3m + 2 * M1 + M2 + X1 + X3 + X4, irreps),
        ir2vec(
            G1p
            + G1m
            + G3p
            + G3m
            + G5p
            + G5m
            + R4p
            + R4m
            + R5p
            + R5m
            + M1
            + M2
            + 3 * M3
            + M4
            + 2 * X1
            + 2 * X2
            + X3
            + X4,
            irreps,
        ),
        ir2vec(
            G2p
            + G2m
            + G3p
            + G3m
            + G4p
            + G4m
            + R4p
            + R4m
            + R5p
            + R5m
            + M1
            + M2
            + M3
            + 3 * M4
            + 2 * X1
            + 2 * X2
            + X3
            + X4,
            irreps,
        ),
        ir2vec(
            G4p
            + G4m
            + G5p
            + G5m
            + R1p
            + R1m
            + R3p
            + R3m
            + R5p
            + R5m
            + 2 * M1
            + 2 * M2
            + M3
            + M4
            + X1
            + X2
            + X3
            + 3 * X4,
            irreps,
        ),
        ir2vec(
            G4p
            + G4m
            + G5p
            + G5m
            + R2p
            + R2m
            + R3p
            + R3m
            + R4p
            + R4m
            + 2 * M1
            + 2 * M2
            + M3
            + M4
            + X1
            + X2
            + 3 * X3
            + X4,
            irreps,
        ),
    ),
    axis=1,
)

In [8]:
print(A)

[[1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0]
 [0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 1]
 [0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 1 1]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1]
 [0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 1]
 [0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 1 

Thanks to this matrix you can transform linear combinations of EBRs into symmetry vectors or linear combinations of irreps using built-in functions

In [9]:
print(ebr2irvec(v=A2g_4b + Eu_4b, ebrs=ebrs, EBR=A))

[0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 2 1 2 1 2 2 1]


In [10]:
ebr2ir(A2g_4b + Eu_4b, ebrs=ebrs, EBR=A, irreps=irreps)

G2p + G3m + G4m + G4p + G5m + M1 + 2*M2 + M3 + 2*M4 + R2p + R3m + R4m + R4p + R5m + X1 + 2*X2 + 2*X3 + X4

## **Main problem :** Find a TETB model from a vector of irreps obtained from the bands of the crystal

First you need to define the vector of irreps you are working with. This can be easily done with built-in functions

In [11]:
vec_test = (
    G1p
    + G1m
    + G2p
    + G5p
    + R1m
    + R2p
    + R4m
    + R5p
    + M1
    + M2
    + M3
    + M4
    + X1
    + X2
    + X3
    + X4
)
vec_test = ir2vec(v=vec_test, irreps=irreps)
print(vec_test)

[1 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1]


With this you can obtain all posible solutions in a list form or only the physical ones. We show here both posibilites for `t=2` number of auxiliary bands

In [12]:
result1 = showAllResults(
    v=vec_test,
    t=2,
    dim=dim_ebrs,
    EBRs=A,
    N_gamma=N_gamma,
    ebrs=ebrs,
    irreps=irreps,
    SG=224,
)
result1

[([2*A2_2a + T2_2a], A2_2a, [False], [-G1p + G4m]),
 ([A1g_4b + A2_2a + A2u_4b, A1g_4c + A2_2a + A2u_4c, A1_2a + A2_2a + T2_2a],
  A1_2a,
  [True, True, True],
  [-G1p + G4m, -G1p + G4m, -G1p + G4m])]

In [13]:
result2 = showOnlyPhysical(
    v=vec_test,
    t=2,
    dim=dim_ebrs,
    EBRs=A,
    N_gamma=N_gamma,
    ebrs=ebrs,
    irreps=irreps,
    SG=224,
)
result2

[(A1g_4b + A2_2a + A2u_4b, A1_2a, -G1p + G4m),
 (A1g_4c + A2_2a + A2u_4c, A1_2a, -G1p + G4m),
 (A1_2a + A2_2a + T2_2a, A1_2a, -G1p + G4m)]

Now let us focus on the case in the case in [article](https://arxiv.org/abs/2305.18257)

In [15]:
chiara = G4m + G2m + R4m + R5p + M1 + 2 * M4 + X1 + X3 + X4
chiara = ir2vec(v=chiara, irreps=irreps)
print(chiara)

[0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 2 1 0 1 1]


In [16]:
result1 = showAllResults(
    v=chiara,
    t=12,
    dim=dim_ebrs,
    EBRs=A,
    N_gamma=N_gamma,
    ebrs=ebrs,
    irreps=irreps,
    SG=224,
)
result1

[([A2g_4c + Eu_4c + T2_2a, A2g_4c + Eg_4b + T2_2a],
  A1u_4b + Eg_4b,
  [False, False],
  [-G1m - G2m + G2p + G3m - G3p + G4m, -G1m - G2m + G2p + G4p - G5m + G5p]),
 ([A2g_4c + Eu_4c + T2_2a, A2g_4c + Eg_4b + T2_2a],
  A1u_4b + Eu_4c,
  [False, False],
  [-G1m - G2m + G2p + G4p - G5m + G5p,
   -G1m - G2m + G2p - G3m + G3p - G4m + 2*G4p - 2*G5m + 2*G5p]),
 ([A2g_4b + Eu_4c + T2_2a, A2g_4b + Eg_4b + T2_2a],
  A1u_4c + Eu_4c,
  [False, False],
  [-G1m - G2m + G2p + G4p - G5m + G5p,
   -G1m - G2m + G2p - G3m + G3p - G4m + 2*G4p - 2*G5m + 2*G5p]),
 ([A2u_4b + Eu_4c + T2_2a, A2u_4b + Eg_4b + T2_2a],
  A1g_4c + Eu_4c,
  [True, True],
  [-G1p + G4m, -G1p - G3m + G3p + G4p - G5m + G5p]),
 ([A2u_4c + Eu_4c + T2_2a, A2u_4c + Eg_4b + T2_2a],
  A1g_4b + Eu_4c,
  [True, True],
  [-G1p + G4m, -G1p - G3m + G3p + G4p - G5m + G5p]),
 ([A1_6d + B1_12f], A1_6d + B1_6d, [True], [-G1m + G4p]),
 ([B1_12f + B1_6d], 2*B1_6d, [True], [-G1m + G4p]),
 ([A2_6d + B1_12f, A2g_4b + A2g_4c + E_2a + T2_2a],
  A2_6d + B

In [41]:
result2 = showOnlyPhysical(
    v=chiara,
    t=2,
    dim=dim_ebrs,
    EBRs=A,
    N_gamma=N_gamma,
    ebrs=ebrs,
    irreps=irreps,
    SG=224,
)
result2

[(A2u_4b + A2u_4c, A1_2a, -G1p + G4m)]

In [42]:
v = G1p + G2p + G3m + R2p + R3m + R4m + M1 + M2 + M4 + X1 + X2 + X3
v = ir2vec(v, irreps)
print(v)

[1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0]


In [43]:
result1 = showAllResults(
    v=v, t=6, dim=dim_ebrs, EBRs=A, N_gamma=N_gamma, ebrs=ebrs, irreps=irreps, SG=224
)
result1

[([A2g_4b + Eg_4c, A2g_4b + Eu_4b],
  T1_2a,
  [False, False],
  [-G1p - G3m + G3p + G4p - G5m + G5p, -G1p + G4m]),
 ([2*A2_2a + Eg_4c, 2*A2_2a + Eu_4b],
  A1u_4b + A2_2a,
  [False, False],
  [-G1p - G3m + G3p + G4p - G5m + G5p, -G1p + G4m]),
 ([A1_2a + A2_2a + Eg_4c, A1_2a + A2_2a + Eu_4b],
  A1_2a + A1u_4b,
  [False, True],
  [-G1p - G3m + G3p + G4p - G5m + G5p, -G1p + G4m])]